graspop.lineup.output-path=graspop.json
spring.datasource.url=jdbc:sqlite:./data/app.db
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.hikari.maximum-pool-size=1
spring.jpa.hibernate.ddl-auto=update
spring.datasource.type=org.springframework.jdbc.datasource.SimpleDriverDataSource
logging.level.com.zaxxer.hikari=WARN
logging.level.org.hibernate.engine.jdbc.env=WARN